### PR TITLE
FACES-2463 Upgrade alloy:row and alloy:column to Bootstrap 3

### PR DESCRIPTION
**Pull request by stiemannkj1**

### CODE REVIEW

**Comment by stiemannkj1** [comment]
@ngriffin7a, #12 must be merged before this.

**Comment by ngriffin7a** [comment]
@stiemannkj1 Since the alloy:row fluid attribute is not available in Bootstrap 3, rather than simply removing the isFluid/setFluid attributes in RowBase.java, perhaps we should `@Override` them in Row.java and log a warning when they are called? Also, the VDLDoc would need to document the fact that it is a no-op for Alloy 3.0.

**Comment by stiemannkj1** [comment]
I think it might be better to deprecate the `fluid` attribute in our next release of Alloy `2.0.x`. Then we can remove it without fear in Alloy `3.0.x`, and we will still be following semantic versioning.

**Comment by ngriffin7a** [comment]
Merged -- please submit a follow-up pull request for the 2.0.x branch that deprecates the fluid attribute. Thank you.

**Comment by stiemannkj1** [comment]
Done in #13

**Pull request closed without merging**
