### PR TITLE
Revert inappropriate copy/paste changes to OverlayRendererBase that occurred in adac3736

### PR DESCRIPTION
**Pull request by stiemannkj1**

### CODE REVIEW

**Comment by stiemannkj1** [comment]
@ngriffin7a, There are major differences between `OverlayRendererBase` in Alloy 2 and Alloy 3 due to ["FACES-2466 Upgrade alloy:dialog to Bootstrap 3."](https://issues.liferay.com/browse/FACES-2466) However, I clobbered those differences in adac373 due to copying/pasting without paying enough attention. This commit simply reverts the changes and fixes the compile failures which adac373 was supposed to fix. Without this commit `alloy:dialog` and `alloy:popover` (and potentially `alloy:tooltip`) are completely broken in Alloy `2.x`.

**Comment by ngriffin7a** [comment]
@stiemannkj1 Is it possible / worth it to create am OverlayRendererBaseCompat.java class in order to isolate differences between the master (3.x) and 2.x branches?

**Comment by ngriffin7a** [comment]
Merged. Thank you.

**Comment by stiemannkj1** [comment]
@ngriffin7a, it looks like both versions still have two methods in common, so that might be a good idea. It might also be a good idea to have `DialogRendererCompat` and `PopoverRendererCompat` to isolate the admittedly minor differences there. Let me know if I should create a task for myself to do this.

**Comment by ngriffin7a** [comment]
@stiemannkj1 Thanks, I created this issue and assigned it to you for after the release: https://issues.liferay.com/browse/FACES-2891

**Pull request merged**
