### PR TITLE
Style alloy:row and alloy:column for the 2.x branch

### PR DESCRIPTION
**Pull request by stiemannkj1**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
@stiemannkj1 What visual/cosmetic problem does this PR solve?

**Comment by stiemannkj1** [comment]
@ngriffin7a, it makes the columns visible like they are in Alloy `3.x`: https://github.com/liferay/liferay-faces-alloy/blob/master/demo/alloy-showcase-webapp/src/main/webapp/WEB-INF/component/alloy/row/column-offset/row.xhtml#L7. It shows where one column ends and another begins and also shows where there is an offset (since that is uncolored). Otherwise there is no real way to tell if the rows and cols are rendered correctly. This is manly just a simple backport of code that's already in `master` (I had to create the `bg-*` classes though since BootStrap 2 doesn't have them).

**Comment by ngriffin7a** [comment]
@stiemannkj1 Is it something we should include in the 2.x version of [alloy.css](https://github.com/liferay/liferay-faces-alloy/blob/2.x/alloy/src/main/resources/META-INF/resources/liferay-faces-alloy/alloy.css)?

**Comment by stiemannkj1** [comment]
@ngriffin7a, no it's strictly for demo purposes. It just turns columns blue and green like this: http://liferayfaces.org/web/guest/alloy-showcase/-/alloy-tag/alloy/row/column-width.

**Comment by ngriffin7a** [comment]
ok <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ngriffin7a** [comment]
Merged, thank you. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
